- name: Install node_exporter for Prometheus
  package:
    name: node_exporter
    state: present

- name: Enable node_exporter
  systemd:
    name: node_exporter
    enabled: true
    state: started
